name: eclass
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.3.3
  go_router: ^13.2.0
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  equatable: ^2.0.5
  jwt_decoder: ^2.0.1
  freezed_annotation: ^2.4.4
  animations: ^2.0.11
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  bloc_test: ^9.1.0
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  freezed: ^2.5.2
  go_router_builder: ^2.3.3
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/logos/
